[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "midiinfo"
dynamic = ["version"]
dependencies = ["python-rtmidi"]
requires-python = ">= 3.9"

[project.scripts]
midiinfo = "midiinfo:main_cli"
